#!/usr/bin/env python

"""
This is a cgi wrapper for querulator.py, basically just there so
*something* still lives when querlator itself tracebacks.
"""

import textwrap
import traceback

try:
	import querulator
	querulator.main()
except SystemExit:
	pass
except Exception, msg:
	print "Content-type: text/html\n"
	print "<head><title>Error</title></head>"
	print "<body><h1>An error has occurred</h1>"
	print "<p>Unless you know exactly why that happened, please"
	print "contact gavo@ari.uni-heidelberg.de with the URL you accessed"
	print "and the following message:</p>"
	print "<pre>"
	print msg.__class__.__name__
	print "\n".join(textwrap.wrap(str(msg)))
	print "</pre>"
	print "<p>Thank you.</p></body>"
	traceback.print_exc()
